### ISSUE TITLE
make_new_github_release(): TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#125]
`oc logs dc/release-bot-user-cont`

```
08:41:55.953 configuration.py  DEBUG  Loaded configuration for user-cont/release-bot
08:41:57.158 utils.py          DEBUG  ['git', 'clone', 'https://github.com/user-cont/release-bot.git', '.']
08:41:57.159 releasebot.py     INFO   release-bot v0.5.0 reporting for duty!
08:41:57.159 github.py         DEBUG  Fetching release-conf.yaml
08:41:57.159 github.py         DEBUG  GET https://api.github.com/repos/user-cont/release-bot/contents/release-conf.yaml
08:41:57.988 github.py         DEBUG  query = query {repository(owner: "user-cont", name: "release-bot") {pullRequests(states: MERGED last: 5 ){
                  edges {
                    cursor
                    node {
                      id
                      title
                      number
                      mergeCommit {
                        oid
                        author {
                            name
                            email
                        }
                      }
                    }
                  }
                }}}
08:41:58.127 github.py         DEBUG  query = query {repository(owner: "user-cont", name: "release-bot") {pullRequests(states: MERGED last: 5 before: "Y3Vyc29yOnYyOpHODeLo0g=="){
                  edges {
                    cursor
                    node {
                      id
                      title
                      number
                      mergeCommit {
                        oid
                        author {
                            name
                            email
                        }
                      }
                    }
                  }
                }}}
08:41:58.283 releasebot.py     INFO   Found merged release PR with version 0.5.0, commit id: b1510bfcfa33d71e50f80f2044b338e72dafa1f3
08:41:58.283 github.py         DEBUG  query = query {repository(owner: "user-cont", name: "release-bot") {releases(last: 1 ){
                        edges{
                         cursor
                         node {
                           isPrerelease
                           isDraft
                           name
                        }
                       }
                     }
                 }}
Traceback (most recent call last):
  File "/opt/app-root/src/.local/bin/release-bot", line 11, in <module>
    load_entry_point('release-bot==0.5.0', 'console_scripts', 'release-bot')()
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/release_bot/releasebot.py", line 300, in main
    rb.run()
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/release_bot/releasebot.py", line 273, in run
    self.make_new_github_release()
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/release_bot/releasebot.py", line 201, in make_new_github_release
    if Version.coerce(latest_github) >= Version.coerce(self.new_release['version']):
  File "/opt/app-root/src/.local/lib/python3.7/site-packages/semantic_version/base.py", line 136, in coerce
    match = base_re.match(version_string)
TypeError: expected string or bytes-like object
```

**Comment by jpopelka** [comment]
[This](https://github.com/user-cont/release-bot/commit/4c0b18dd1532b79d7459df57d03903b6a1b25d95#diff-a2053831ac76bc378a135c94c55b5125L225) is the cause @TomasTomecek

**Comment by TomasTomecek** [comment]
and I thought I caught all of them
